@startuml components

title "Example of architecture of the git server system"

component system {
    portin "2222" as i2222

    component backup_storage
    component backup_utility
    component logs_access
    component configuration as sys_config
    component sshd

    component container <<container>> {
        portin "*" as blank

        component logs
        component configuration
    }
}

actor "system administrator" as admin
component deployment_system

admin --> i2222

i2222 --> sshd
sys_config <- sshd
sshd --> blank
sshd -> logs_access

deployment_system --> system
logs_access --> logs
backup_utility --> container
backup_utility --> backup_storage
sshd --> backup_utility

@enduml
