@startuml sequence_git

actor developer
boundary "ssh\nserver" as sshd
boundary "git auth layer" as git_auth_layer
participant "git server" as git_server

developer -> sshd: git command, over SSH
sshd -> git_auth_layer: git command,\nSSH public key
git_auth_layer -> git_auth_layer: verify authorization
git_auth_layer -> git_server: run git command
git_server --> git_auth_layer: git objects
git_auth_layer --> sshd: git objects
sshd --> developer: git objects

@enduml

@startuml sequence_lfs

actor developer
boundary "sshd" as sshd
boundary "reverse proxy" as nginx
boundary "git auth layer" as git_auth_layer
participant "git-lfs-authenticate\ncommand\nimplementation" as git_lfs_authenticate
participant "git lfs server" as lfs_info_server
database "file storage" as fs

group#LightGoldenRodYellow Authenticate
    developer -> sshd: git-lfs-authenticate, over SSH
    sshd -> git_auth_layer: git-lfs-authenticate,\nSSH public key
    git_auth_layer -> git_lfs_authenticate: run command git-lfs-authenticate
    git_lfs_authenticate --> git_auth_layer: POA
    git_auth_layer --> sshd: POA
    sshd --> developer: POA
end

group#LightCoral Batch api
    developer -> nginx: https POST /batch/objects, POA
    nginx -> lfs_info_server: http POST /batch/objects, POA
    lfs_info_server -> lfs_info_server: verify POA
    lfs_info_server -> fs: check existence
    fs --> lfs_info_server: existence
    lfs_info_server -> lfs_info_server: sign urls
    lfs_info_server --> nginx: signed urls
    nginx --> developer: signed urls
end

alt#LightBlue Download object, with the git-lfs-server verifying the url
    developer -> nginx: GET https /url-to-object?sign=...
    nginx -> lfs_info_server: GET http /url-to-object?sign=...
    lfs_info_server -> lfs_info_server: verify sign
    lfs_info_server -> fs : request object
    fs --> lfs_info_server : object
    lfs_info_server --> nginx: object
    nginx --> developer: object
else Download object, with the file storage verifying the url directly
    developer -> nginx: GET https /url-to-object?sign=...
    nginx -> fs: GET /url-to-object?sign=...
    fs -> fs: verify sign
    fs --> nginx: object
    nginx --> developer: object
end

@enduml
