FROM rust:1.72 as builder
WORKDIR /app
COPY . .
RUN cargo build --release --bin lfs-info-server

FROM ubuntu:22.04 AS runtime
WORKDIR /app
RUN apt-get update && apt-get install -y openssl
COPY --from=builder "/app/target/release/lfs-info-server" "/usr/local/bin/server"
EXPOSE 3000
ENTRYPOINT ["/usr/local/bin/server"]

